<?php
/**
 * PH2M_PhLaposteGenerateLabel
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category   LaposteGenerateLabel
 * @copyright  Copyright (c) 2017 PH2M SARL
 * @author     Bastien | PH2M SARL <contact@ph2m.com> : http://www.ph2m.com/
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 * @var $this PH2M_PhLaposteGenerateLabel_Block_Sales_Order_View_Exchange
 */

?>
<h1><?php echo $this->__('Generate Label') ?></h1>
<?php $_orders = $this->listOfOrderAvailable(); ?>
<?php if($_orders->getSize()): ?>
    <?php echo $this->getChildHtml('cms_describe_first_method'); ?>
    <div class="dl-button">
        <form action="<?php echo $this->helper('lapostegeneratelabel')->getDownloadControllerUrl() ?>" method="post">
            <select name="order_id">
                <?php foreach ($_orders as $_order): ?>
                    <option value="<?php echo $_order->getId() ?>"><?php echo $this->__('Order #') . ' ' . $_order->getIncrementId() ?></option>
                <?php endforeach; ?>
            </select>
            <button class="button" type="submit">
                    <span>
                        <span><?php echo $this->__('Download label') ?></span>
                    </span>
            </button>
            <p><?php echo '(' . $this->__('pdf format') . ')'; ?></p>
        </form>
    </div>
<?php else: ?>
    <p class="text-center"><?php echo $this->__('Sorry, but for return a product you need a complete order in country allowed') ?></p>
<?php endif; ?>