<?php
/**
 * PH2M_PhLaposteGenerateLabel
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category   LaposteGenerateLabel
 * @copyright  Copyright (c) 2017 PH2M SARL
 * @author     PH2M | Bastien Lamamy (bastienlm) bastien-lamamy.com/
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 * $this PH2M_PhLaposteGenerateLabel_Block_Sales_Order_View
 */

?>
<?php if($this->canShowButton()): ?>
    <a href="<?php echo $this->helper('lapostegeneratelabel')->getViewControllerUrl() . 'order/' .$this->getOrder()->getId()  ?>"><?php echo $this->__('Generate Label') ?></a>
<?php endif; ?>